name: Tests

on:
  push:
    branches: [main]
    paths:
      - "custom_components/**"
      - "requirements_test.txt"
      - "pytest.ini"
      - ".github/workflows/tests.yml"
      - "**/tests/**"
  pull_request:
    branches: [main]
    paths:
      - "custom_components/**"
      - "requirements_test.txt"
      - "pytest.ini"
      - ".github/workflows/tests.yml"
      - "**/tests/**"

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements_test.txt

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run tests with coverage
        env:
          PYTHONWARNINGS: "ignore::UserWarning:homeassistant.requirements"
        run: |
          pytest -vv --durations=10 --maxfail=1 \
                 --cov=custom_components/swos \
                 --cov-report=term-missing \
                 --cov-report=xml:coverage.xml

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          if-no-files-found: warn
